jobs:
  build:
    executor:
      name: node/default
      tag: '14.15.3'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
orbs:
  node: circleci/node@1.1.6
version: 2.1
